[project]
name = "d23-lop4-nhom16"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "vid-prepper>=0.1.2",
]

[project.scripts]
d23-lop4-nhom16 = "d23_lop4_nhom16:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
